sbt.InvalidScalaInstance: Scala instance doesn't exist or is invalid:  (library jar  /home/user/bigdata/scala-2.10.4/lib/scala-library.jar)
	at sbt.ScalaInstance$.slowActualVersion(ScalaInstance.scala:125)
	at sbt.ScalaInstance$.sbt$ScalaInstance$$actualVersion(ScalaInstance.scala:122)
	at sbt.ScalaInstance$.apply(ScalaInstance.scala:77)
	at sbt.ScalaInstance$.apply(ScalaInstance.scala:64)
	at sbt.Defaults$$anonfun$scalaInstanceFromHome$1.apply(Defaults.scala:396)
	at sbt.Defaults$$anonfun$scalaInstanceFromHome$1.apply(Defaults.scala:395)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: scala.tools.nsc.Properties
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at sbt.ScalaInstance$.slowActualVersion(ScalaInstance.scala:125)
	at sbt.ScalaInstance$.sbt$ScalaInstance$$actualVersion(ScalaInstance.scala:122)
	at sbt.ScalaInstance$.apply(ScalaInstance.scala:77)
	at sbt.ScalaInstance$.apply(ScalaInstance.scala:64)
	at sbt.Defaults$$anonfun$scalaInstanceFromHome$1.apply(Defaults.scala:396)
	at sbt.Defaults$$anonfun$scalaInstanceFromHome$1.apply(Defaults.scala:395)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[0m[[31merror[0m] [0m(*:[31mscalaInstance[0m) sbt.InvalidScalaInstance: Scala instance doesn't exist or is invalid:  (library jar  /home/user/bigdata/scala-2.10.4/lib/scala-library.jar)[0m
